// h dev seed-cdi
// deno run -A ./.scripts/seed-cdi.ts

import * as yaml from "jsr:@std/yaml";
import * as path from "jsr:@std/path";

import { listComposeFiles, paths } from "../routines/paths.js";

async function main() {
  const sourceFiles = await listComposeFiles().then((files) =>
    files.filter((name) => name.includes(".nvidia.") && !name.endsWith(".build.yml"))
  );

  for (const file of sourceFiles) {
    const outName = file.replace(".nvidia.", ".cdi.");
    const serviceName = resolveServiceName(file);

    // Carry over the nvidia.yml's `environment:` block, if any. Most GPU
    // images derive from an nvidia/cuda base that already sets
    // NVIDIA_DRIVER_CAPABILITIES, so this is usually empty — but a service
    // whose own image isn't CUDA-based needs it declared explicitly, and
    // that must survive into the CDI variant too, not just the nvidia one.
    const sourcePath = path.join(paths.services, file);
    const sourceDoc = yaml.parse(await Deno.readTextFile(sourcePath));
    const environment = sourceDoc.services?.[serviceName]?.environment;
    const environmentBlock = Array.isArray(environment) && environment.length > 0
      ? `    environment:\n${environment.map((e) => `      - ${e}`).join("\n")}\n`
      : "";

    const content =
      `
# This file is generated by seed-cdi.ts script,
# any updates will be overwritten.
services:
  ${serviceName}:
${environmentBlock}    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              capabilities: [gpu]
              device_ids:
              - nvidia.com/gpu=all
    `.trim() + "\n";

    const outPath = path.join(paths.services, outName);
    console.log(`Writing ${outPath}...`);
    await Deno.writeTextFile(outPath, content);
  }

  console.log("Done!");
}

function resolveServiceName(filename: string) {
  const ignored = new Set(["compose", "x", "nvidia", "yml"]);
  const parts = filename.split(".").filter((part) => !ignored.has(part));

  if (parts.length !== 1) {
    throw new Error(
      `Unsupported seed Nvidia file: ${filename}, update the seed-cdi script`
    );
  }

  return parts[0];
}

main().catch(console.error);
