dataRoot: ./data
listen: false
protocol:
  ipv4: true
  ipv6: false
dnsPreferIPv6: false
autorunHostname: auto
port: 8000
autorunPortOverride: -1
whitelistMode: true
enableForwardedWhitelist: true
whitelist:
  - ::1
  - 127.0.0.1
basicAuthMode: false
basicAuthUser:
  username: user
  password: password
enableCorsProxy: false
requestProxy:
  enabled: false
  url: socks5://username:password@example.com:1080
  bypass:
    - localhost
    - 127.0.0.1
enableUserAccounts: false
enableDiscreetLogin: false
sessionTimeout: 86400
cookieSecret: 2q4EfGXc+Evo9gg+s0aD2mLCqsOTY6lCXCkR2mbqdPuhZ2cqR8YOtT1I/UGCyTdahuwGUMAr/FsQ+enZiR7cGA==
disableCsrfProtection: false
securityOverride: false
autorun: true
avoidLocalhost: false
disableThumbnails: false
thumbnailsQuality: 95
avatarThumbnailsPng: false
allowKeysExposure: false
skipContentCheck: false
disableChatBackup: false
numberOfBackups: 50
chatBackupThrottleInterval: 10000
whitelistImportDomains:
  - localhost
  - cdn.discordapp.com
  - files.catbox.moe
  - raw.githubusercontent.com
requestOverrides: []
enableExtensions: true
enableExtensionsAutoUpdate: true
enableDownloadableTokenizers: true
vectors:
  enableModelScopes: false
extras:
  disableAutoDownload: false
  classificationModel: Cohee/distilbert-base-uncased-go-emotions-onnx
  captioningModel: Xenova/vit-gpt2-image-captioning
  embeddingModel: Cohee/jina-embeddings-v2-base-en
  promptExpansionModel: Cohee/fooocus_expansion-onnx
  speechToTextModel: Xenova/whisper-small
  textToSpeechModel: Xenova/speecht5_tts
openai:
  randomizeUserId: false
  captionSystemPrompt: ""
deepl:
  formality: default
mistral:
  enablePrefix: false
ollama:
  keepAlive: -1
claude:
  enableSystemPromptCache: false
enableServerPlugins: false
